[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
# healthcheck désactivé temporairement pour debug
# healthcheckPath = "/health"
# healthcheckTimeout = 300
restartPolicyType = "always"

[environment]
NODE_ENV = "production"
